In [1]:
import sklearn
import numpy as np
import pandas as pd

In [2]:
from sklearn import datasets
iris = datasets.load_iris()
x = iris.data
y = iris.target

In [3]:
print(x.shape, y.shape)
print(x.dtype, y.dtype)
print(iris.feature_names)
#print(x)
#print(y)

(150, 4) (150,)
float64 int64
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
df = pd.DataFrame(x, columns=iris.feature_names)
df['target'] = y
#df

In [5]:
df.head()
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
145       2  
146       2  
147       2  
148       2  
149       2

In [6]:
from sklearn.utils import shuffle
df = shuffle(df).reset_index(drop=True)
df.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                4.9               3.1                1.5               0.1   
1                5.8               2.7                5.1               1.9   
2                4.9               3.6                1.4               0.1   
3                5.8               2.6                4.0               1.2   
4                5.8               2.7                4.1               1.0   
5                6.5               3.2                5.1               2.0   
6                5.6               2.7                4.2               1.3   
7                5.1               3.8                1.6               0.2   
8                5.5               2.6                4.4               1.2   
9                6.7               3.3                5.7               2.1   

   target  
0       0  
1       2  
2       0  
3       1  
4       1  
5       2  
6       1  
7       0  
8       1  
9       2

In [7]:
y = df['target']
df.drop('target', axis=1, inplace=True)
x = np.array(df)
print(x.shape, y.shape)
print(x.dtype, y.dtype)

(150, 4) (150,)
float64 int64


In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2)
print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

(120, 4) (120,) (30, 4) (30,)


In [9]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [10]:
y_pred = knn.predict(x_test)
y_pred = np.array(y_pred)
y_test = np.array(y_test)
#for i in range(len(y_pred)):
#    print(y_pred[i], y_test[i])

In [11]:
from sklearn import metrics
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test,y_pred))
print(metrics.accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.58      1.00      0.74         7
           2       1.00      0.62      0.76        13

   micro avg       0.83      0.83      0.83        30
   macro avg       0.86      0.87      0.83        30
weighted avg       0.90      0.83      0.84        30

[[10  0  0]
 [ 0  7  0]
 [ 0  5  8]]
0.8333333333333334


In [12]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [13]:
y_pred = dtc.predict(x_test)
y_pred = np.array(y_pred)
y_test = np.array(y_test)
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.86      0.86      0.86         7
           2       0.92      0.92      0.92        13

   micro avg       0.93      0.93      0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

[[10  0  0]
 [ 0  6  1]
 [ 0  1 12]]
0.9333333333333333


In [14]:
import os
dotfile = open("tree.dot", "w")
sklearn.tree.export_graphviz(dtc, out_file=dotfile, feature_names=iris.feature_names, class_names=iris.target_names)
dotfile.close()
os.system("dot -Tpng tree.dot -o tree.png")

0

In [15]:
import pickle
pickle.dump(dtc, open('dtc', 'wb'))
loaded_model = pickle.load(open('dtc', 'rb'))
loaded_model.predict([[6.9, 3.2, 5.7, 2]])

array([2])